#!/usr/bin/env python3
"""Inline the chart files into index.html so the playground works from a
local file as well as over http. Run this after editing anything in charts/."""
import io, re, os

CHARTS = [
    ("Flashcards",    "charts/flashcards.html"),
    ("Russian Cases", "charts/russian-case-compass.html"),
]

BEGIN = "<!-- CHART SOURCES: generated by build-charts.py, do not edit by hand -->"
END = "<!-- END CHART SOURCES -->"

scene_defs = io.open("scenes/scenes.json", encoding="utf-8").read()
blocks = [BEGIN,
          '<script type="application/json" id="scene-defs">%s</script>' % scene_defs,
          '<div id="chart-sources" hidden>']
for name, path in CHARTS:
    html = io.open(path, encoding="utf-8").read()
    # The HTML parser ends a script block at the first </script, so escape it.
    html = html.replace("</script", "<\\/script")
    blocks.append(
        '  <script type="text/plain" data-chart="%s" data-file="./%s">%s</script>'
        % (name, path, html)
    )
blocks.append("</div>")
blocks.append(END)
payload = "\n".join(blocks)

index = io.open("index.html", encoding="utf-8").read()
if BEGIN in index:
    index = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: payload, index, flags=re.S)
else:
    anchor = '<script>\n(function () {'
    index = index.replace(anchor, payload + "\n\n" + anchor, 1)

io.open("index.html", "w", encoding="utf-8").write(index)
print("inlined %d charts (%d KB)" % (len(CHARTS), len(payload) // 1024))
